// Code generated by MockGen. DO NOT EDIT.
// Source: internal/songs/usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/songs/usecase.go -destination=internal/songs/mock/mock_song_usecase.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/Worwulew/Songs-library/internal/model"
	utils "github.com/Worwulew/Songs-library/pkg/utils"
	gomock "go.uber.org/mock/gomock"
)

// MockUseCase is a mock of UseCase interface.
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
	isgomock struct{}
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase.
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance.
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUseCase) Create(ctx context.Context, song *model.Song) (*model.Song, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, song)
	ret0, _ := ret[0].(*model.Song)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUseCaseMockRecorder) Create(ctx, song any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUseCase)(nil).Create), ctx, song)
}

// Delete mocks base method.
func (m *MockUseCase) Delete(ctx context.Context, songID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, songID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUseCaseMockRecorder) Delete(ctx, songID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUseCase)(nil).Delete), ctx, songID)
}

// GetSongText mocks base method.
func (m *MockUseCase) GetSongText(ctx context.Context, songID uint, query *utils.PaginationQuery) (*model.VersesList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSongText", ctx, songID, query)
	ret0, _ := ret[0].(*model.VersesList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSongText indicates an expected call of GetSongText.
func (mr *MockUseCaseMockRecorder) GetSongText(ctx, songID, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSongText", reflect.TypeOf((*MockUseCase)(nil).GetSongText), ctx, songID, query)
}

// SongsByFields mocks base method.
func (m *MockUseCase) SongsByFields(ctx context.Context, title, group string, query *utils.PaginationQuery) (*model.SongsList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SongsByFields", ctx, title, group, query)
	ret0, _ := ret[0].(*model.SongsList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SongsByFields indicates an expected call of SongsByFields.
func (mr *MockUseCaseMockRecorder) SongsByFields(ctx, title, group, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SongsByFields", reflect.TypeOf((*MockUseCase)(nil).SongsByFields), ctx, title, group, query)
}

// Update mocks base method.
func (m *MockUseCase) Update(ctx context.Context, song *model.Song) (*model.Song, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, song)
	ret0, _ := ret[0].(*model.Song)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockUseCaseMockRecorder) Update(ctx, song any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUseCase)(nil).Update), ctx, song)
}
