// Code generated by MockGen. DO NOT EDIT.
// Source: internal/songs/pg_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/songs/pg_repository.go -destination=internal/songs/mock/mock_song_pg_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/Worwulew/Songs-library/internal/model"
	utils "github.com/Worwulew/Songs-library/pkg/utils"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, song *model.Song) (*model.Song, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, song)
	ret0, _ := ret[0].(*model.Song)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, song any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, song)
}

// Delete mocks base method.
func (m *MockRepository) Delete(ctx context.Context, songID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, songID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder) Delete(ctx, songID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), ctx, songID)
}

// GetSongText mocks base method.
func (m *MockRepository) GetSongText(ctx context.Context, songID uint, query *utils.PaginationQuery) (*model.VersesList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSongText", ctx, songID, query)
	ret0, _ := ret[0].(*model.VersesList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSongText indicates an expected call of GetSongText.
func (mr *MockRepositoryMockRecorder) GetSongText(ctx, songID, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSongText", reflect.TypeOf((*MockRepository)(nil).GetSongText), ctx, songID, query)
}

// SongsByFields mocks base method.
func (m *MockRepository) SongsByFields(ctx context.Context, title, group string, query *utils.PaginationQuery) (*model.SongsList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SongsByFields", ctx, title, group, query)
	ret0, _ := ret[0].(*model.SongsList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SongsByFields indicates an expected call of SongsByFields.
func (mr *MockRepositoryMockRecorder) SongsByFields(ctx, title, group, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SongsByFields", reflect.TypeOf((*MockRepository)(nil).SongsByFields), ctx, title, group, query)
}

// Update mocks base method.
func (m *MockRepository) Update(ctx context.Context, song *model.Song) (*model.Song, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, song)
	ret0, _ := ret[0].(*model.Song)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(ctx, song any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), ctx, song)
}
